### ISSUE TITLE
Problem with Python dependencies

### ISSUE THREAD

**Issue by BYAchraf** [institut-galilee/Lab-One#4]
dans le TP1 lorsque j'écrit make m'affiche cette erreur:

/home/achraf/Documents/Master/Master1/IoT/TPs/esp-idf/make/project.mk:476 : la recette pour la cible « check_python_dependencies » a échouée
make: *** [check_python_dependencies] Erreur 1

Si vous pouvez m'aider SVP

**Comment by HamidiMassinissa** [comment]
Test this

```
cd /home/achraf/Documents/Master/Master1/IoT/TPs/
virtualenv -p python2.7 env-toto
source env-toto/bin/activate
pip install -r /home/achraf/Documents/Master/Master1/IoT/TPs/esp-idf/requirements.txt
```

**Comment by BYAchraf** [comment]
au lieu de 
`pip -r install .../requirements.txt`
vous écrivez
`pip install -r .../requirements.txt`
