### ISSUE TITLE
make: *** Aucune règle pour fabriquer la cible

### ISSUE THREAD

**Issue by LEBSIRAHLAM** [institut-galilee/Lab-One#9]
Can someone help me please  to resolve this error: i tried several times but always the same error message
1-so i did this:
~/Documents/master/IOT$ sudo git clone --recursive https://github.com/institut-galilee/esp-idf
all was download..
 and i've this:
:~/Documents/master/IOT/esp-idf/examples/get-started/hello_world$ make
Makefile:8: /home/ahlam/Documents/master/IOT/make/project.mk: Aucun fichier ou dossier de ce type
make: *** Aucune règle pour fabriquer la cible « /home/ahlam/Documents/master/IOT/make/project.mk ». Arrêt.

**Comment by HamidiMassinissa** [comment]
Can you provide the output you get when you run these two commands:
* `echo $IDF_PATH`
* `echo $PATH`

**Comment by LEBSIRAHLAM** [comment]
i've this:
echo $IDF_PATH
/home/ahlam/Documents/master/IOT

but for the $PATH:
/u01/app/oracle/product/11.2.0/xe/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/ahlam/eclipse/java-2018-12/eclipse:/opt/xtensa-esp32-elf/bin

**Comment by HamidiMassinissa** [comment]
The second path, seems ok. However, for the first, I think you should get something like this:
```
/home/ahlam/Documents/master/IOT/ ... /esp-idf
```
Whatever is in-between, you must get `esp-idf` at the end.

So you have to reset your $IDF_PATH with the right path.

**Comment by BYAchraf** [comment]
Try to modify the $IDF_PATH in the bashrc file:
<s>`$IDF_PATH=/home/ahlam/Documents/master/IOT`</s>

`IDF_PATH=~/Documents/master/IOT/esp-idf`

**Comment by BYAchraf** [comment]
I'm so sorry they are not `$` before `IDF_PATH`
so the line will be
`IDF_PATH=~/Documents/master/IOT/esp-idf`

**Comment by LEBSIRAHLAM** [comment]
thanks @HamidiMassinissa & @BYAchraf  for your answers it's finally working.!! :)))))))
